"""Shared transport/sync contract constants for bridge, recorder, and analysis."""

SYNC_PACKET_SCHEMA_VERSION = 1

PACKET_MODE_LATEST_PARALLEL = "latest_parallel"
PACKET_MODE_PACKET_SHADOW = "packet_shadow"
PACKET_MODE_PACKET_FIFO_ACTIVE = "packet_fifo_active"

PACKET_CONSUME_POLICY_FIFO_STRICT = "fifo_strict"
PACKET_CONSUME_POLICY_FRESHEST_WITHIN_BUDGET = "freshest_within_budget"
PACKET_CONSUME_POLICY_LATEST_DEBUG = "latest_debug"

PACKET_SELECTION_SOURCE_NONE = "none"
PACKET_SELECTION_SOURCE_SERVER = "server_selector"
PACKET_SELECTION_SOURCE_LATEST_DEBUG = "latest_debug"
PACKET_SELECTION_SOURCE_LEGACY = "legacy"

PACKET_JOIN_SOURCE_NONE = "none"
PACKET_JOIN_SOURCE_PACKET_KEY = "packet_key"
PACKET_JOIN_SOURCE_UNITY_FRAME_FALLBACK = "unity_frame_fallback"

PACKET_FALLBACK_NONE = "none"
PACKET_FALLBACK_MISSING_FRONT_CAMERA = "missing_front_camera"
PACKET_FALLBACK_MISSING_VEHICLE_STATE = "missing_vehicle_state"
PACKET_FALLBACK_PACKET_TIMEOUT = "packet_timeout"
PACKET_FALLBACK_PACKET_QUEUE_OVERFLOW = "packet_queue_overflow"
PACKET_FALLBACK_PACKET_LEGACY_PATH = "packet_legacy_path"
PACKET_FALLBACK_PAYLOAD_STALE_TIMEOUT = "payload_stale_timeout"
PACKET_FALLBACK_PAYLOAD_STALE_DROP = "payload_stale_drop"
PACKET_FALLBACK_PAYLOAD_AGE_BUDGET_EXCEEDED = "payload_age_budget_exceeded"
PACKET_FALLBACK_PAYLOAD_DRAIN_CAP = "payload_drain_cap"

POST_JUMP_REASON_NONE = "none"
POST_JUMP_REASON_TELEPORT_GUARD = "teleport_guard"
POST_JUMP_REASON_EXPLICIT_RESET = "explicit_reset"
POST_JUMP_REASON_UNKNOWN = "unknown"

TELEPORT_GUARD_REASON_NONE = "none"
TELEPORT_GUARD_REASON_TRUE_DISCONTINUITY = "true_discontinuity"
TELEPORT_GUARD_REASON_HARD_OVERRIDE = "hard_override"
TELEPORT_GUARD_REASON_EXPECTED_MOTION_CONSISTENT = "expected_motion_consistent"
TELEPORT_GUARD_REASON_CONTINUITY_SUPPRESSED = "continuity_suppressed"

EFFECTIVE_TARGET_REASON_FREE_FLOW = "free_flow_target"
EFFECTIVE_TARGET_REASON_ACC_FOLLOW = "acc_follow"
EFFECTIVE_TARGET_REASON_CURVE_CAP = "curve_cap"
EFFECTIVE_TARGET_REASON_FEASIBILITY_BACKSTOP = "feasibility_backstop"
EFFECTIVE_TARGET_REASON_POST_JUMP_COOLDOWN = "post_jump_cooldown"
EFFECTIVE_TARGET_REASON_FALLBACK_UNKNOWN = "fallback_unknown"
