"""Shared transport/sync contract constants for bridge, recorder, and analysis."""

SYNC_PACKET_SCHEMA_VERSION = 1

PACKET_MODE_LATEST_PARALLEL = "latest_parallel"
PACKET_MODE_PACKET_SHADOW = "packet_shadow"
PACKET_MODE_PACKET_FIFO_ACTIVE = "packet_fifo_active"

PACKET_CONSUME_POLICY_FIFO_STRICT = "fifo_strict"
PACKET_CONSUME_POLICY_FRESHEST_WITHIN_BUDGET = "freshest_within_budget"
PACKET_CONSUME_POLICY_LATEST_DEBUG = "latest_debug"

PACKET_SELECTION_SOURCE_NONE = "none"
PACKET_SELECTION_SOURCE_SERVER = "server_selector"
PACKET_SELECTION_SOURCE_LATEST_DEBUG = "latest_debug"
PACKET_SELECTION_SOURCE_LEGACY = "legacy"

PACKET_JOIN_SOURCE_NONE = "none"
PACKET_JOIN_SOURCE_PACKET_KEY = "packet_key"
PACKET_JOIN_SOURCE_UNITY_FRAME_FALLBACK = "unity_frame_fallback"

PACKET_SELECTION_RESULT_NONE = "none"
PACKET_SELECTION_RESULT_COMPLETE = "complete"
PACKET_SELECTION_RESULT_COMPLETE_COHERENT = "complete_coherent"
PACKET_SELECTION_RESULT_COMPLETE_INCOHERENT = "complete_incoherent"
PACKET_SELECTION_RESULT_FALLBACK = "fallback"
PACKET_SELECTION_RESULT_LEGACY = "legacy"

PACKET_COHERENCE_REASON_COHERENT = "coherent"
PACKET_COHERENCE_REASON_FRONT_VEHICLE_TIME_DELTA_BUDGET_EXCEEDED = (
    "front_vehicle_time_delta_budget_exceeded"
)
PACKET_COHERENCE_REASON_FRONT_VEHICLE_FRAME_DELTA_BUDGET_EXCEEDED = (
    "front_vehicle_frame_delta_budget_exceeded"
)
PACKET_COHERENCE_REASON_JOIN_WAIT_BUDGET_EXCEEDED = "join_wait_budget_exceeded"
PACKET_COHERENCE_REASON_COMPONENT_AGE_BUDGET_EXCEEDED = (
    "component_age_budget_exceeded"
)
PACKET_COHERENCE_REASON_MISSING_COMPONENT_TIMESTAMP = "missing_component_timestamp"

PACKET_SELECTED_FAILURE_CONTRACT_NONE = "none"
PACKET_SELECTED_FAILURE_CONTRACT_VEHICLE_NOT_BUILT = "vehicle_not_built"
PACKET_SELECTED_FAILURE_CONTRACT_VEHICLE_NOT_ENQUEUED = "vehicle_not_enqueued"
PACKET_SELECTED_FAILURE_CONTRACT_VEHICLE_NOT_SENT = "vehicle_not_sent"
PACKET_SELECTED_FAILURE_CONTRACT_VEHICLE_SUPERSEDED_BEFORE_SEND = (
    "vehicle_superseded_before_send"
)
PACKET_SELECTED_FAILURE_CONTRACT_CAMERA_NOT_REQUESTED = "camera_not_requested"
PACKET_SELECTED_FAILURE_CONTRACT_CAMERA_NOT_SENT = "camera_not_sent"
PACKET_SELECTED_FAILURE_CONTRACT_CAMERA_REQUEST_NOT_ATTEMPTED = (
    "camera_request_not_attempted"
)
PACKET_SELECTED_FAILURE_CONTRACT_CAMERA_REQUEST_REJECTED = (
    "camera_request_rejected"
)
PACKET_SELECTED_FAILURE_CONTRACT_CAMERA_REQUEST_EXPIRED_BEFORE_CAPTURE = (
    "camera_request_expired_before_capture"
)
PACKET_SELECTED_FAILURE_CONTRACT_CAMERA_REQUESTED_NOT_SENT = (
    "camera_requested_not_sent"
)
PACKET_SELECTED_FAILURE_CONTRACT_BUNDLE_ABORTED_CAMERA_REQUEST_NOT_ATTEMPTED = (
    "bundle_aborted_camera_request_not_attempted"
)
PACKET_SELECTED_FAILURE_CONTRACT_BUNDLE_ABORTED_CAMERA_REQUEST_REJECTED = (
    "bundle_aborted_camera_request_rejected"
)
PACKET_SELECTED_FAILURE_CONTRACT_BUNDLE_ABORTED_CAMERA_REQUEST_BUDGET_EXCEEDED = (
    "bundle_aborted_camera_request_budget_exceeded"
)
PACKET_SELECTED_FAILURE_CONTRACT_BUNDLE_ABORTED_CAMERA_CAPTURE_MISSING = (
    "bundle_aborted_camera_capture_missing"
)
PACKET_SELECTED_FAILURE_CONTRACT_SOURCE_BUNDLE_DEADLINE_EXPIRED = (
    "source_bundle_deadline_expired"
)
PACKET_SELECTED_FAILURE_CONTRACT_BRIDGE_JOIN_FAILURE = "bridge_join_failure"

PACKET_SELECTED_FAILURE_STAGE_NONE = "none"
PACKET_SELECTED_FAILURE_STAGE_SOURCE_BUNDLE = "source_bundle"
PACKET_SELECTED_FAILURE_STAGE_CAMERA_CAPTURE = "camera_capture"
PACKET_SELECTED_FAILURE_STAGE_BRIDGE_JOIN = "bridge_join"

PACKET_JOIN_FAILURE_NONE = "none"
PACKET_JOIN_FAILURE_CAMERA_KEY_MISSING = "camera_key_missing"
PACKET_JOIN_FAILURE_VEHICLE_KEY_MISSING = "vehicle_key_missing"
PACKET_JOIN_FAILURE_PACKET_KEY_MISMATCH = "packet_key_mismatch"
PACKET_JOIN_FAILURE_CAMERA_COMPONENT_LATE = "camera_component_late"
PACKET_JOIN_FAILURE_VEHICLE_COMPONENT_LATE = "vehicle_component_late"
PACKET_JOIN_FAILURE_JOIN_WINDOW_EXPIRED = "join_window_expired"
PACKET_JOIN_FAILURE_SUPERSEDED_CAMERA = "superseded_camera"
PACKET_JOIN_FAILURE_SUPERSEDED_VEHICLE = "superseded_vehicle"
PACKET_JOIN_FAILURE_SOURCE_BUNDLE_ABORTED = "source_bundle_aborted"

PACKET_JOIN_FAILURE_SIDE_NONE = "none"
PACKET_JOIN_FAILURE_SIDE_CAMERA = "camera"
PACKET_JOIN_FAILURE_SIDE_VEHICLE = "vehicle"
PACKET_JOIN_FAILURE_SIDE_BOTH = "both"

PACKET_FALLBACK_NONE = "none"
PACKET_FALLBACK_MISSING_FRONT_CAMERA = "missing_front_camera"
PACKET_FALLBACK_MISSING_VEHICLE_STATE = "missing_vehicle_state"
PACKET_FALLBACK_PACKET_TIMEOUT = "packet_timeout"
PACKET_FALLBACK_PACKET_QUEUE_OVERFLOW = "packet_queue_overflow"
PACKET_FALLBACK_PACKET_LEGACY_PATH = "packet_legacy_path"
PACKET_FALLBACK_PAYLOAD_STALE_TIMEOUT = "payload_stale_timeout"
PACKET_FALLBACK_PAYLOAD_STALE_DROP = "payload_stale_drop"
PACKET_FALLBACK_PAYLOAD_AGE_BUDGET_EXCEEDED = "payload_age_budget_exceeded"
PACKET_FALLBACK_PAYLOAD_DRAIN_CAP = "payload_drain_cap"

POST_JUMP_REASON_NONE = "none"
POST_JUMP_REASON_TELEPORT_GUARD = "teleport_guard"
POST_JUMP_REASON_EXPLICIT_RESET = "explicit_reset"
POST_JUMP_REASON_UNKNOWN = "unknown"

TELEPORT_GUARD_REASON_NONE = "none"
TELEPORT_GUARD_REASON_TRUE_DISCONTINUITY = "true_discontinuity"
TELEPORT_GUARD_REASON_HARD_OVERRIDE = "hard_override"
TELEPORT_GUARD_REASON_EXPECTED_MOTION_CONSISTENT = "expected_motion_consistent"
TELEPORT_GUARD_REASON_CONTINUITY_SUPPRESSED = "continuity_suppressed"

EFFECTIVE_TARGET_REASON_FREE_FLOW = "free_flow_target"
EFFECTIVE_TARGET_REASON_ACC_FOLLOW = "acc_follow"
EFFECTIVE_TARGET_REASON_CURVE_CAP = "curve_cap"
EFFECTIVE_TARGET_REASON_FEASIBILITY_BACKSTOP = "feasibility_backstop"
EFFECTIVE_TARGET_REASON_POST_JUMP_COOLDOWN = "post_jump_cooldown"
EFFECTIVE_TARGET_REASON_FALLBACK_UNKNOWN = "fallback_unknown"
